services:
  - type: web
    name: tieba-feedback-bot
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r bot/requirements.txt
    startCommand: python bot/main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        value: 137458/tieba-lite-harmony
      - key: MEOW_NICKNAME
        value: isczjk
      - key: RENDER_URL
        sync: false